#!/bin/bash
# _scripts/check-regression.sh <benchstat_output_or_ratio_file> [baseline_ratio_file]

# This script performs two types of regression detection:
# 1. Absolute Regression: Checks if Ours is significantly slower than Standard (Ratio > 1.1).
# 2. Relative Regression: Checks if the current Speedup Factor has degraded vs Baseline (> 10%).

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <current_ratio.txt> [baseline_ratio.txt]"
    exit 1
fi

CURRENT_RATIO=$1
BASELINE_RATIO=$2

REGRESSION_FOUND=0

# --- 1. Absolute Regression Check (Ours vs Standard) ---
# In ratio files generated by bench-ratio, 'ns/op' is (Ours/Std)*1000.
# A value > 1100.0 means Ours is > 10% slower than Standard.
echo "Checking Absolute Performance (vs Standard Library)..."
while read -r line; do
    if [[ $line =~ Benchmark.+[[:space:]]+1[[:space:]]+([0-9.]+)[[:space:]]+ns/op ]]; then
        val=${BASH_REMATCH[1]}
        name=$(echo "$line" | awk '{print $1}')
        # Check if slower than standard library (with 10% grace margin)
        if (( $(echo "$val > 1100.0" | bc -l) )); then
            speedup=$(echo "scale=2; 1000 / $val" | bc -l)
            echo "::error::[Absolute Regression] $name is SLOWER than Standard (Speedup: ${speedup}x)"
            REGRESSION_FOUND=1 
        fi
    fi
done < "$CURRENT_RATIO"

# --- 2. Relative Regression Check (Current vs Baseline) ---
if [ -n "$BASELINE_RATIO" ] && [ -s "$BASELINE_RATIO" ]; then
    echo "Checking Relative Performance Delta (vs Baseline)..."
    DELTA_FILE=$(mktemp)
    go tool benchstat "$BASELINE_RATIO" "$CURRENT_RATIO" > "$DELTA_FILE"
    
    # Parse benchstat output for regressions
    # Format: ns/op  500 ± 5%  600 ± 5%  +20.00%  (p=0.008 n=5+5)
    # We look for '+' followed by >= 10% change, with significant p-value.
    # Note: We exclude '~' (not significant)
    REGRESSIONS=$(grep -E "\+([1-9][0-9]|[1-9][0-9][0-9]+)\.[0-9]+%" "$DELTA_FILE" | grep -v "~" | grep "p=" || true)
    
    if [ -n "$REGRESSIONS" ]; then
        echo "::error::Significant Performance Regressions Detected (>10%):"
        echo "$REGRESSIONS"
        REGRESSION_FOUND=1
    else
        echo "No significant relative regressions detected."
    fi
    rm "$DELTA_FILE"
fi

exit $REGRESSION_FOUND
